# System Exploration (Security)

Parsing the data and understanding it (System attribute)

In [5]:
import json
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from anomaly_detection.etl.load import load_records, load_system_df

plt.style.use('ggplot')

In [6]:
# Path to the data
project_folder = Path.cwd().parent

output_path = project_folder / "data/system_exploration/security"

evtx_path = project_folder / "data/raw/93_securitelog.evtx"

evtx_path

WindowsPath('c:/Users/hp/Documents/School/anomaly-detection/data/raw/93_securitelog.evtx')

In [7]:
records = load_records(evtx_path)

len(records)

31466

In [8]:
with open(project_folder / "data/processed/record.txt", "w", encoding="utf-8") as file:
    file.write(json.dumps(
        records[0],
        indent=4
    ))

records[0]

{'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
 'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
   'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
  'EventID': 4624,
  'Version': 2,
  'Level': 0,
  'Task': 12544,
  'Opcode': 0,
  'Keywords': '0x8020000000000000',
  'TimeCreated': {'SystemTime': '2026-06-17T00:15:07.799161Z'},
  'EventRecordID': 34978816,
  'Correlation': {'ActivityID': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01'},
  'Execution': {'ProcessID': 940, 'ThreadID': 5960},
  'Channel': 'Security',
  'Computer': 'ESANTE.carte.com.tn',
  'Security': None},
 'EventData': {'SubjectUserSid': 'S-1-5-18',
  'SubjectUserName': 'ESANTE$',
  'SubjectDomainName': 'CARTE',
  'SubjectLogonId': '0x3e7',
  'TargetUserSid': 'S-1-5-21-3333335972-2113272682-612058519-500',
  'TargetUserName': 'Administrateur',
  'TargetDomainName': 'ESANTE',
  'TargetLogonId': '0x77061c91',
  'LogonType': 4,
  'LogonProcessName': 'Advapi  ',
  'AuthenticationPackageName': 'Negotiate',
  'WorkstationName': 'ESANTE',
  'LogonGuid': '00000000-0000-0000-0000-000000000000',
  'TransmittedServices': '-',
  'LmPackageName': '-',
  'KeyLength': 0,
  'ProcessId': '0x898',
  'ProcessName': 'C:\\Windows\\System32\\svchost.exe',
  'IpAddress': '-',
  'IpPort': '-',
  'ImpersonationLevel': '%%1833',
  'RestrictedAdminMode': '-',
  'TargetOutboundUserName': '-',
  'TargetOutboundDomainName': '-',
  'VirtualAccount': '%%1843',
  'TargetLinkedLogonId': '0x0',
  'ElevatedToken': '%%1842'}}

In [9]:
system_df = load_system_df(evtx_path)

system_df.head()

,EventID,Version,Level,Task,Opcode,Keywords,EventRecordID,Channel,Computer,Provider_Name,Provider_Guid,TimeCreated_SystemTime,Correlation_ActivityID,Execution_ProcessID,Execution_ThreadID
0,4624,2,0,12544,0,0x8020000000000000,34978816,Security,ESANTE.carte.com.tn,Microsoft-Windows-Security-Auditing,54849625-5478-4994-A5BA-3E3B0328C30D,2026-06-17T00:15:07.799161Z,F1DAB952-E970-0004-5DB9-DAF170E9DC01,940,5960
1,4672,0,0,12548,0,0x8020000000000000,34978817,Security,ESANTE.carte.com.tn,Microsoft-Windows-Security-Auditing,54849625-5478-4994-A5BA-3E3B0328C30D,2026-06-17T00:15:07.799169Z,F1DAB952-E970-0004-5DB9-DAF170E9DC01,940,5960
2,4634,0,0,12545,0,0x8020000000000000,34978818,Security,ESANTE.carte.com.tn,Microsoft-Windows-Security-Auditing,54849625-5478-4994-A5BA-3E3B0328C30D,2026-06-17T00:15:08.470381Z,NaN,940,5960
3,4634,0,0,12545,0,0x8020000000000000,34978819,Security,ESANTE.carte.com.tn,Microsoft-Windows-Security-Auditing,54849625-5478-4994-A5BA-3E3B0328C30D,2026-06-17T00:15:55.134677Z,NaN,940,6940
4,4776,0,0,14336,0,0x8020000000000000,34978820,Security,ESANTE.carte.com.tn,Microsoft-Windows-Security-Auditing,54849625-5478-4994-A5BA-3E3B0328C30D,2026-06-17T00:16:00.615230Z,F1DAB952-E970-0001-3651-E8F170E9DC01,940,6940

In [10]:
system_df.columns

Index(['EventID', 'Version', 'Level', 'Task', 'Opcode', 'Keywords',
       'EventRecordID', 'Channel', 'Computer', 'Provider_Name',
       'Provider_Guid', 'TimeCreated_SystemTime', 'Correlation_ActivityID',
       'Execution_ProcessID', 'Execution_ThreadID'],
      dtype='str')

# EventID

In [11]:
events_df = pd.DataFrame(system_df['EventID'].value_counts())

total_events = events_df['count'].sum()

events_df['percentage'] = (events_df['count'] / total_events) * 100

events_df

         count  percentage
EventID
4624      6336    20.13602
4672      6335   20.132842
4634      6194   19.684739
4648      6189   19.668849
4776      6185   19.656137
4799       109    0.346406
4702        49    0.155724
5379        30    0.095341
4662        11    0.034958
4697        11    0.034958
4798         9    0.028602
4611         3    0.009534
5058         1    0.003178
5061         1    0.003178
5059         1    0.003178
4699         1    0.003178
4698         1    0.003178

In [12]:
keep_list = events_df[events_df['count'] > 10]

keep_list.index

Index([4624, 4672, 4634, 4648, 4776, 4799, 4702, 5379, 4662, 4697], dtype='Int64', name='EventID')

In [13]:
# Add the descriptions to the event IDs
event_descriptions = {
    "4624": "An account was successfully logged on",
    "4672": "Special privileges assigned to new logon",
    "4634": "An account was logged off",
    "4648": "A logon was attempted using explicit credentials",
    "4776": "The computer attempted to validate the credentials for an account",
    "4799": "A security-enabled local group membership was enumerated",
    "4702": "A scheduled task was updated",
    "5379": "Credential Manager credentials were read",
    "4662": "An operation was performed on an object",
    "4697": "A service was installed in the system",
    "4798": "A user's local group membership was enumerated",
    "4611": "A trusted logon process has been registered with the Local Security Authority",
    "5058": "Key file operation",
    "5061": "Cryptographic operation",
    "5059": "Key migration operation",
    "4699": "A scheduled task was deleted",
    "4698": "A scheduled task was created",
}

desc_series = pd.Series(event_descriptions, name='description')
desc_series.index = desc_series.index.astype(events_df.index.dtype)  # match dtype (str vs int)

events_df = events_df.join(desc_series)

events_df.to_csv(output_path / "events.txt")

events_df

         count  percentage                                        description
EventID
4624      6336    20.13602              An account was successfully logged on
4672      6335   20.132842           Special privileges assigned to new logon
4634      6194   19.684739                          An account was logged off
4648      6189   19.668849   A logon was attempted using explicit credentials
4776      6185   19.656137  The computer attempted to validate the credent...
4799       109    0.346406  A security-enabled local group membership was ...
4702        49    0.155724                       A scheduled task was updated
5379        30    0.095341           Credential Manager credentials were read
4662        11    0.034958            An operation was performed on an object
4697        11    0.034958              A service was installed in the system
4798         9    0.028602     A user's local group membership was enumerated
4611         3    0.009534  A trusted logon process has been registered wi...
5058         1    0.003178                                 Key file operation
5061         1    0.003178                            Cryptographic operation
5059         1    0.003178                            Key migration operation
4699         1    0.003178                       A scheduled task was deleted
4698         1    0.003178                       A scheduled task was created

In [14]:
unique_event_ids = [4611, 5058, 5061, 5059, 4699, 4698]

unique_events = [record for record in records if record['System']['EventID'] in unique_event_ids]

with open(output_path / "unique_event_records.txt", "w", encoding="utf-8") as file:
    file.write(json.dumps(
        unique_events,
        indent=4
    ))

unique_events

[{'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 4611,
   'Version': 0,
   'Level': 0,
   'Task': 12289,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:35.572564Z'},
   'EventRecordID': 35010093,
   'Correlation': {'ActivityID': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01'},
   'Execution': {'ProcessID': 940, 'ThreadID': 6200},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-18',
   'SubjectUserName': 'ESANTE$',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x3e7',
   'LogonProcessName': 'Winlogon'}},
 {'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 4611,
   'Version': 0,
   'Level': 0,
   'Task': 12289,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:35.574661Z'},
   'EventRecordID': 35010094,
   'Correlation': {'ActivityID': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01'},
   'Execution': {'ProcessID': 940, 'ThreadID': 6200},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-18',
   'SubjectUserName': 'ESANTE$',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x3e7',
   'LogonProcessName': 'UserManager'}},
 {'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 4611,
   'Version': 0,
   'Level': 0,
   'Task': 12289,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:35.862661Z'},
   'EventRecordID': 35010098,
   'Correlation': {'ActivityID': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01'},
   'Execution': {'ProcessID': 940, 'ThreadID': 6200},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-18',
   'SubjectUserName': 'ESANTE$',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x3e7',
   'LogonProcessName': 'UserManager'}},
 {'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 5058,
   'Version': 1,
   'Level': 0,
   'Task': 12292,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:39.055201Z'},
   'EventRecordID': 35010115,
   'Correlation': None,
   'Execution': {'ProcessID': 940, 'ThreadID': 5792},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-21-3073298170-276159943-2983424533-500',
   'SubjectUserName': 'Administrateur',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x7903aaa8',
   'ClientProcessId': 6320,
   'ClientCreationTime': '2026-06-17T09:48:37.621590Z',
   'ProviderName': 'Microsoft Software Key Storage Provider',
   'AlgorithmName': 'UNKNOWN',
   'KeyName': 'Microsoft Connected Devices Platform device certificate',
   'KeyType': '%%2500',
   'KeyFilePath': 'C:\\Users\\Administrateur.CARTE\\AppData\\Roaming\\Microsoft\\Crypto\\Keys\\de7cf8a7901d2ad13e5c67c29e5d1662_86d17e09-0875-4485-884a-274defc77995',
   'Operation': '%%2458',
   'ReturnCode': '0x0'}},
 {'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 5061,
   'Version': 0,
   'Level': 0,
   'Task': 12290,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:39.085918Z'},
   'EventRecordID': 35010116,
   'Correlation': None,
   'Execution': {'ProcessID': 940, 'ThreadID': 5792},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-21-3073298170-276159943-2983424533-500',
   'SubjectUserName': 'Administrateur',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x7903aaa8',
   'ProviderName': 'Microsoft Software Key Storage Provider',
   'AlgorithmName': 'ECDSA_P256',
   'KeyName': 'Microsoft Connected Devices Platform device certificate',
   'KeyType': '%%2500',
   'Operation': '%%2480',
   'ReturnCode': '0x0'}},
 {'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 5059,
   'Version': 1,
   'Level': 0,
   'Task': 12292,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:39.094633Z'},
   'EventRecordID': 35010117,
   'Correlation': None,
   'Execution': {'ProcessID': 940, 'ThreadID': 5792},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-21-3073298170-276159943-2983424533-500',
   'SubjectUserName': 'Administrateur',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x7903aaa8',
   'ClientProcessId': 6320,
   'ClientCreationTime': '2026-06-17T09:48:37.621590Z',
   'ProviderName': 'Microsoft Software Key Storage Provider',
   'AlgorithmName': 'ECDSA_P256',
   'KeyName': 'Microsoft Connected Devices Platform device certificate',
   'KeyType': '%%2500',
   'Operation': '%%2464',
   'ReturnCode': '0x0'}},
 {'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 4699,
   'Version': 1,
   'Level': 0,
   'Task': 12804,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:41.758655Z'},
   'EventRecordID': 35010120,
   'Correlation': {'ActivityID': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01'},
   'Execution': {'ProcessID': 940, 'ThreadID': 5792},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-21-3073298170-276159943-2983424533-500',
   'SubjectUserName': 'Administrateur',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x7903aaa8',
   'TaskName': '\\CreateExplorerShellUnelevatedTask',
   'TaskContent': '',
   'ClientProcessStartKey': 14636698789317551,
   'ClientProcessId': 7800,
   'ParentProcessId': 5348,
   'RpcCallClientLocality': 0,
   'FQDN': 'ESANTE.carte.com.tn'}},
 {'#attributes': {'xmlns': 'http://schemas.microsoft.com/win/2004/08/events/event'},
  'System': {'Provider': {'Name': 'Microsoft-Windows-Security-Auditing',
    'Guid': '54849625-5478-4994-A5BA-3E3B0328C30D'},
   'EventID': 4698,
   'Version': 1,
   'Level': 0,
   'Task': 12804,
   'Opcode': 0,
   'Keywords': '0x8020000000000000',
   'TimeCreated': {'SystemTime': '2026-06-17T09:48:41.798436Z'},
   'EventRecordID': 35010121,
   'Correlation': {'ActivityID': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01'},
   'Execution': {'ProcessID': 940, 'ThreadID': 5792},
   'Channel': 'Security',
   'Computer': 'ESANTE.carte.com.tn',
   'Security': None},
  'EventData': {'SubjectUserSid': 'S-1-5-21-3073298170-276159943-2983424533-500',
   'SubjectUserName': 'Administrateur',
   'SubjectDomainName': 'CARTE',
   'SubjectLogonId': '0x7903aaa8',
   'TaskName': '\\CreateExplorerShellUnelevatedTask',
   'TaskContent': '<?xml version="1.0" encoding="UTF-16"?>\r\n<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\r\n  <RegistrationInfo>\r\n    <Author>ExplorerShellUnelevated</Author>\r\n    <URI>\\CreateExplorerShellUnelevatedTask</URI>\r\n  </RegistrationInfo>\r\n  <Triggers>\r\n    <RegistrationTrigger id="CreateExplorerShell_Trigger">\r\n      <Enabled>true</Enabled>\r\n      <Delay>PT0S</Delay>\r\n    </RegistrationTrigger>\r\n  </Triggers>\r\n  <Settings>\r\n    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\r\n    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\r\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\r\n    <AllowHardTerminate>true</AllowHardTerminate>\r\n    <StartWhenAvailable>true</StartWhenAvailable>\r\n    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>\r\n    <IdleSettings>\r\n      <Duration>PT10M</Duration>\r\n      <WaitTimeout>PT1H</WaitTimeout>\r\n      <StopOnIdleEnd>true</StopOnIdleEnd>\r\n      <RestartOnIdle>false</RestartOnIdle>\r\n    </IdleSettings>\r\n    <AllowStartOnDemand>true</AllowStartOnDemand>\r\n    <Enabled>true</Enabled>\r\n    <Hidden>false</Hidden>\r\n    <RunOnlyIfIdle>false</RunOnlyIfIdle>\r\n    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>\r\n    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\r\n    <WakeToRun>false</WakeToRun>\r\n    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>\r\n    <Priority>6</Priority>\r\n  </Settings>\r\n  <Actions Context="Author">\r\n    <Exec>\r\n      <Command>C:\\WINDOWS\\Explorer.EXE</Command>\r\n      <Arguments>/NOUACCHECK</Arguments>\r\n    </Exec>\r\n  </Actions>\r\n  <Principals>\r\n    <Principal id="Author">\r\n      <UserId>CARTE\\Administrateur</UserId>\r\n      <LogonType>InteractiveToken</LogonType>\r\n      <RunLevel>LeastPrivilege</RunLevel>\r\n    </Principal>\r\n  </Principals>\r\n</Task>',
   'ClientProcessStartKey': 14636698789317551,
   'ClientProcessId': 7800,
   'ParentProcessId': 5348,
   'RpcCallClientLocality': 0,
   'FQDN': 'ESANTE.carte.com.tn'}}]

# Correlation

In [15]:
correlation_activity_df = pd.DataFrame(system_df['Correlation_ActivityID'].value_counts())

correlation_activity_df

                                      count
Correlation_ActivityID
F1DAB952-E970-0004-5DB9-DAF170E9DC01  19084
F1DAB952-E970-0001-3651-E8F170E9DC01      1
F1DAB952-E970-0004-F545-A1F270E9DC01      1
F1DAB952-E970-0002-B68E-E4F170E9DC01      1
F1DAB952-E970-000B-A3FA-ECF170E9DC01      1
...                                     ...
F1DAB952-E970-0003-F748-4FF370E9DC01      1
F1DAB952-E970-000A-C5C0-07F270E9DC01      1
F1DAB952-E970-000B-2F1B-EDF170E9DC01      1
F1DAB952-E970-0003-F848-4FF370E9DC01      1
F1DAB952-E970-0000-56F9-EDF170E9DC01      1

[6186 rows x 1 columns]

In [16]:
main_corr_id = system_df[system_df["Correlation_ActivityID"] == "F1DAB952-E970-0004-5DB9-DAF170E9DC01"]["EventID"].value_counts()
other_corr_id = system_df[system_df["Correlation_ActivityID"] != "F1DAB952-E970-0004-5DB9-DAF170E9DC01"]["EventID"].value_counts()

corr_comparison_df = pd.concat(
    [main_corr_id, other_corr_id],
    axis=1,
    keys=['MainCorrelationActivityID', 'OtherCorrelationActivityID']
)

corr_comparison_df = corr_comparison_df.fillna(0)

corr_comparison_df

         MainCorrelationActivityID  OtherCorrelationActivityID
EventID
4624                          6336                           0
4672                          6335                           0
4648                          6189                           0
4799                           109                           0
4702                            49                           0
5379                            30                           0
4662                            11                           0
4697                            11                           0
4798                             9                           0
4611                             3                           0
4699                             1                           0
4698                             1                           0
4634                             0                        6194
4776                             0                        6185
5058                             0                           1
5061                             0                           1
5059                             0                           1

# Execution

In [17]:
execution_df = pd.DataFrame(system_df[['Execution_ProcessID', 'Execution_ThreadID']].value_counts())

execution_df

                                        count
Execution_ProcessID Execution_ThreadID
940                 6940                 6938
                    6016                 6788
                    5132                  502
                    7172                  453
                    7480                  447
...                                       ...
                    6828                    4
                    2732                    4
                    8732                    4
                    3968                    4
                    9752                    4

[171 rows x 1 columns]

In [18]:
eventid_to_threadid_df = pd.crosstab(system_df["Execution_ThreadID"], system_df["EventID"])

eventid_to_threadid_df

EventID,4611,4624,4634,4648,4662,4672,4697,4698,4699,4702,4776,4798,4799,5058,5059,5061,5379
Execution_ThreadID,,,,,,,,,,,,,,,,,
132,0,65,67,65,0,65,0,0,0,1,65,0,0,0,0,0,0
972,0,49,48,48,0,49,0,0,0,0,48,0,0,0,0,0,0
1012,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0
1164,0,26,19,24,0,26,0,0,0,1,24,0,0,0,0,0,0
1176,0,7,7,6,0,7,0,0,0,0,6,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9116,0,13,12,13,0,13,0,0,0,0,13,0,0,0,0,0,0
9176,0,11,11,11,0,11,0,0,0,0,11,0,0,0,0,0,0
9196,0,17,18,17,0,17,0,0,0,0,17,0,0,0,0,0,0
9204,0,26,30,26,0,26,0,0,0,0,26,0,0,0,0,0,0
9752,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0

# Others

In [19]:
provider_df = pd.DataFrame(system_df[['Provider_Name', 'Provider_Guid']].value_counts())

provider_df

                                                                          count
Provider_Name                       Provider_Guid
Microsoft-Windows-Security-Auditing 54849625-5478-4994-A5BA-3E3B0328C30D  31466

In [20]:
system_df.astype(str).nunique()

EventID                      17
Version                       3
Level                         1
Task                         10
Opcode                        1
Keywords                      1
EventRecordID             31466
Channel                       1
Computer                      1
Provider_Name                 1
Provider_Guid                 1
TimeCreated_SystemTime    31465
Correlation_ActivityID     6186
Execution_ProcessID           1
Execution_ThreadID          171
dtype: int64

In [21]:
constants_df = pd.DataFrame(system_df[['Level', 'Opcode', 'Keywords', 'Channel', 'Computer', 'Execution_ProcessID']].value_counts())

constants_df.to_csv(output_path / "constants.csv")

constants_df

                                                                                  count
Level Opcode Keywords           Channel  Computer            Execution_ProcessID
0     0      0x8020000000000000 Security ESANTE.carte.com.tn 940                  31466

In [22]:
eventid_to_task_df = pd.crosstab(system_df["Task"], system_df["EventID"])

eventid_to_task_df

EventID,4611,4624,4634,4648,4662,4672,4697,4698,4699,4702,4776,4798,4799,5058,5059,5061,5379
Task,,,,,,,,,,,,,,,,,
12289,3,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0
12290,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
12292,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
12544,0,6336,0,6189,0,0,0,0,0,0,0,0,0,0,0,0,0
12545,0,0,6194,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12548,0,0,0,0,0,6335,0,0,0,0,0,0,0,0,0,0,0
12804,0,0,0,0,11,0,0,1,1,49,0,0,0,0,0,0,0
13824,0,0,0,0,0,0,0,0,0,0,0,9,0,0,0,0,30
13826,0,0,0,0,0,0,0,0,0,0,0,0,109,0,0,0,0
14336,0,0,0,0,0,0,0,0,0,0,6185,0,0,0,0,0,0

In [23]:
version_df = pd.DataFrame(system_df['Version'].value_counts())

version_df

         count
Version
0        25066
2         6336
1           64

In [24]:
eventid_to_version_df = pd.crosstab(system_df["Version"], system_df["EventID"])

eventid_to_version_df

EventID,4611,4624,4634,4648,4662,4672,4697,4698,4699,4702,4776,4798,4799,5058,5059,5061,5379
Version,,,,,,,,,,,,,,,,,
0,3,0,6194,6189,11,6335,0,0,0,0,6185,9,109,0,0,1,30
1,0,0,0,0,0,0,11,1,1,49,0,0,0,1,1,0,0
2,0,6336,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0