# Testing the transformers

In [1]:
import pandas as pd

from pathlib import Path
from anomaly_detection.parser.data_parsers import parse_system, parse_security, parse_application
from anomaly_detection.transformers import system_transformer, application_transformer, security_transformer

c:\Users\hp\AppData\Local\pypoetry\Cache\virtualenvs\anomaly-detection-mxkT3iGB-py3.12\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Path to the data
project_folder = Path.cwd().parent

output_path = project_folder / "data/parsing"

security_evtx_path = project_folder / "data/raw/93_securitelog.evtx"
application_evtx_path = project_folder / "data/raw/93_applog.evtx"
system_evtx_path = project_folder / "data/raw/93_syslog.evtx"

application_evtx_path

WindowsPath('c:/Users/hp/Documents/School/anomaly-detection/data/raw/93_applog.evtx')

# System

In [3]:
system_training_records = parse_system(system_evtx_path)

system_training_records[0]

{'timestamp': {'day_sin': np.float64(-0.433883739117558),
  'second_sin': np.float64(-0.9781476007338056),
  'minute_cos': np.float64(0.9781476007338057),
  'hour_sin': np.float64(0.8660254037844386),
  'minute_sin': np.float64(-0.20791169081775898),
  'month_sin': np.float64(1.0),
  'hour_cos': np.float64(0.5000000000000001),
  'month_cos': np.float64(6.123233995736766e-17),
  'deltatime': Timedelta('0 days 00:02:19.046309'),
  'second_cos': np.float64(0.20791169081775943),
  'day_cos': np.float64(-0.9009688679024191)},
 'profile': {'event_record_id': 210478,
  'correlation_activity_id': None,
  'event_id': 7036,
  'version': 0,
  'previous_event_id': 7036,
  'event_id_frequency': np.float64(0.9060706937218755),
  'execution_thread_id': 5368},
 'data': {'process_name': None,
  'session_id': None,
  'new_value': None,
  'old_value': None,
  'actor': None,
  'status': 'en cours d’exécution',
  'entity': 'Service de transfert intelligent en arrière-plan',
  'context': None}}

In [4]:
flat_system_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in system_training_records]

flat_system_training_record[0]

{'day_sin': np.float64(-0.433883739117558),
 'second_sin': np.float64(-0.9781476007338056),
 'minute_cos': np.float64(0.9781476007338057),
 'hour_sin': np.float64(0.8660254037844386),
 'minute_sin': np.float64(-0.20791169081775898),
 'month_sin': np.float64(1.0),
 'hour_cos': np.float64(0.5000000000000001),
 'month_cos': np.float64(6.123233995736766e-17),
 'deltatime': Timedelta('0 days 00:02:19.046309'),
 'second_cos': np.float64(0.20791169081775943),
 'day_cos': np.float64(-0.9009688679024191),
 'event_record_id': 210478,
 'correlation_activity_id': None,
 'event_id': 7036,
 'version': 0,
 'previous_event_id': 7036,
 'event_id_frequency': np.float64(0.9060706937218755),
 'execution_thread_id': 5368,
 'process_name': None,
 'session_id': None,
 'new_value': None,
 'old_value': None,
 'actor': None,
 'status': 'en cours d’exécution',
 'entity': 'Service de transfert intelligent en arrière-plan',
 'context': None}

In [5]:
system_training_df = pd.DataFrame(flat_system_training_record)

system_training_df.head(10)

,day_sin,second_sin,minute_cos,hour_sin,minute_sin,month_sin,hour_cos,month_cos,deltatime,second_cos,...,event_id_frequency,execution_thread_id,process_name,session_id,new_value,old_value,actor,status,entity,context
0,-0.433884,-0.978148,0.978148,0.866025,-0.207912,1.0,0.500000,6.123234e-17,0 days 00:02:19.046309,0.207912,...,0.906071,5368.0,NaN,NaN,None,None,NaN,en cours d’exécution,Service de transfert intelligent en arrière-plan,None
1,-0.433884,-0.978148,0.978148,0.866025,-0.207912,1.0,0.500000,6.123234e-17,0 days 00:00:00.031244,0.207912,...,0.077569,5368.0,NaN,NaN,Démarrage automatique,Démarrage à la demande,NaN,None,Service de transfert intelligent en arrière-plan,None
2,-0.433884,-0.978148,0.978148,0.866025,-0.207912,1.0,0.500000,6.123234e-17,0 days 00:00:00.328128,0.207912,...,0.906071,9040.0,NaN,NaN,None,None,NaN,en cours d’exécution,Carte de performance WMI,None
3,-0.433884,-0.951057,1.000000,0.965926,0.000000,1.0,0.258819,6.123234e-17,0 days 00:02:00.756168,0.309017,...,0.906071,8788.0,NaN,NaN,None,None,NaN,arrêté,Carte de performance WMI,None
4,-0.433884,-0.951057,0.978148,0.965926,0.207912,1.0,0.258819,6.123234e-17,0 days 00:02:00.011128,0.309017,...,0.077569,4480.0,NaN,NaN,Démarrage à la demande,Démarrage automatique,NaN,None,Service de transfert intelligent en arrière-plan,None
5,-0.433884,-0.951057,0.978148,0.965926,0.207912,1.0,0.258819,6.123234e-17,0 days 00:00:00.031255,0.309017,...,0.906071,4480.0,NaN,NaN,None,None,NaN,arrêté,Service de transfert intelligent en arrière-plan,None
6,-0.433884,0.207912,0.500000,0.965926,0.866025,1.0,0.258819,6.123234e-17,0 days 00:07:14.224809,0.978148,...,0.906071,8076.0,NaN,NaN,None,None,NaN,en cours d’exécution,Service de licences de client (ClipSVC),None
7,-0.433884,0.207912,0.500000,0.965926,0.866025,1.0,0.258819,6.123234e-17,0 days 00:00:00.109375,0.978148,...,0.906071,6080.0,NaN,NaN,None,None,NaN,en cours d’exécution,Assistant Connexion avec un compte Microsoft,None
8,-0.433884,0.207912,0.500000,0.965926,0.866025,1.0,0.258819,6.123234e-17,0 days 00:00:00.047848,0.978148,...,0.906071,8076.0,NaN,NaN,None,None,NaN,en cours d’exécution,Optimisation de livraison,None
9,-0.433884,0.309017,0.500000,0.965926,0.866025,1.0,0.258819,6.123234e-17,0 days 00:00:01.063972,0.951057,...,0.906071,8076.0,NaN,NaN,None,None,NaN,en cours d’exécution,Service de déploiement AppX (AppXSVC),None

In [6]:
system_transformer.fit_transform(system_training_df)

array([[1.39046309e+02,            nan, 0.00000000e+00, ...,
        9.06070694e-01, 5.36800000e+03,            nan],
       [3.12440000e-02,            nan, 1.00000000e+00, ...,
        7.75690460e-02, 5.36800000e+03,            nan],
       [3.28128000e-01,            nan, 0.00000000e+00, ...,
        9.06070694e-01, 9.04000000e+03,            nan],
       ...,
       [3.95648470e+01,            nan, 0.00000000e+00, ...,
        9.06070694e-01, 2.30800000e+03,            nan],
       [6.00367230e+01,            nan, 0.00000000e+00, ...,
        9.06070694e-01, 2.30800000e+03,            nan],
       [1.09289650e+01,            nan, 0.00000000e+00, ...,
        9.06070694e-01, 2.30800000e+03,            nan]],
      shape=(59779, 47))

# Application

In [7]:
application_training_records = parse_application(application_evtx_path)

application_training_records[0]

{'timestamp': {'day_sin': np.float64(-0.433883739117558),
  'second_sin': np.float64(0.0),
  'minute_cos': np.float64(0.913545457642601),
  'hour_sin': np.float64(0.49999999999999994),
  'minute_sin': np.float64(-0.40673664307580015),
  'month_sin': np.float64(1.2246467991473532e-16),
  'hour_cos': np.float64(-0.8660254037844387),
  'month_cos': np.float64(-1.0),
  'deltatime': Timedelta('0 days 00:00:20.289018'),
  'second_cos': np.float64(1.0),
  'day_cos': np.float64(-0.9009688679024191)},
 'profile': {'event_record_id': 2899035,
  'correlation_activity_id': None,
  'event_id': 4,
  'version': None,
  'previous_event_id': 4,
  'event_id_frequency': np.float64(0.9653113448962184),
  'execution_thread_id': None},
 'data': {'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")',
  'entity': None}}

In [8]:
flat_application_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in application_training_records]

flat_application_training_record[0]

{'day_sin': np.float64(-0.433883739117558),
 'second_sin': np.float64(0.0),
 'minute_cos': np.float64(0.913545457642601),
 'hour_sin': np.float64(0.49999999999999994),
 'minute_sin': np.float64(-0.40673664307580015),
 'month_sin': np.float64(1.2246467991473532e-16),
 'hour_cos': np.float64(-0.8660254037844387),
 'month_cos': np.float64(-1.0),
 'deltatime': Timedelta('0 days 00:00:20.289018'),
 'second_cos': np.float64(1.0),
 'day_cos': np.float64(-0.9009688679024191),
 'event_record_id': 2899035,
 'correlation_activity_id': None,
 'event_id': 4,
 'version': None,
 'previous_event_id': 4,
 'event_id_frequency': np.float64(0.9653113448962184),
 'execution_thread_id': None,
 'context': 'php[8696] | PHP Warning: PHP Startup: Unable to load dynamic library \'php_pdo_sqlsrv_74_ts_x64.dll\' (tried: c:/wamp/bin/php/php7.4.0/ext/php_pdo_sqlsrv_74_ts_x64.dll (%1 n’est pas une application Win32 valide.), c:/wamp/bin/php/php7.4.0/ext/php_php_pdo_sqlsrv_74_ts_x64.dll.dll (Le module spécifié est introuvable.)) (php  "C:\\wamp\\www\\CARTENET\\library\\App\\Jobs\\Ckeckifsigned.php")',
 'entity': None}

In [9]:
application_training_df = pd.DataFrame(flat_application_training_record)

application_training_df.head(10)

,day_sin,second_sin,minute_cos,hour_sin,minute_sin,month_sin,hour_cos,month_cos,deltatime,second_cos,day_cos,event_record_id,correlation_activity_id,event_id,version,previous_event_id,event_id_frequency,execution_thread_id,context,entity
0,-0.433884,0.000000,0.913545,0.5,-0.406737,1.224647e-16,-0.866025,-1.0,0 days 00:00:20.289018,1.000000,-0.900969,2899035,None,4,NaN,4,0.965311,NaN,php[8696] | PHP Warning: PHP Startup: Unable t...,NaN
1,-0.433884,0.309017,0.913545,0.5,-0.406737,1.224647e-16,-0.866025,-1.0,0 days 00:00:02.662888,0.951057,-0.900969,2899036,None,4,NaN,4,0.965311,NaN,php[8736] | PHP Warning: PHP Startup: Unable t...,NaN
2,-0.433884,0.309017,0.913545,0.5,-0.406737,1.224647e-16,-0.866025,-1.0,0 days 00:00:00.062795,0.951057,-0.900969,2899037,None,4,NaN,4,0.965311,NaN,php[8456] | PHP Warning: PHP Startup: Unable t...,NaN
3,-0.433884,0.309017,0.913545,0.5,-0.406737,1.224647e-16,-0.866025,-1.0,0 days 00:00:00,0.951057,-0.900969,2899038,None,4,NaN,4,0.965311,NaN,php[4500] | PHP Warning: PHP Startup: Unable t...,NaN
4,-0.433884,0.309017,0.913545,0.5,-0.406737,1.224647e-16,-0.866025,-1.0,0 days 00:00:00.015626,0.951057,-0.900969,2899039,None,4,NaN,4,0.965311,NaN,php[3664] | PHP Warning: PHP Startup: Unable t...,NaN
5,-0.433884,0.000000,0.978148,0.5,-0.207912,1.224647e-16,-0.866025,-1.0,0 days 00:01:57.258522,1.000000,-0.900969,2899040,None,4,NaN,4,0.965311,NaN,php[1176] | PHP Warning: PHP Startup: Unable t...,NaN
6,-0.433884,0.309017,0.978148,0.5,-0.207912,1.224647e-16,-0.866025,-1.0,0 days 00:00:02.284295,0.951057,-0.900969,2899041,None,4,NaN,4,0.965311,NaN,php[3704] | PHP Warning: PHP Startup: Unable t...,NaN
7,-0.433884,0.309017,0.978148,0.5,-0.207912,1.224647e-16,-0.866025,-1.0,0 days 00:00:00,0.951057,-0.900969,2899042,None,4,NaN,4,0.965311,NaN,php[3664] | PHP Warning: PHP Startup: Unable t...,NaN
8,-0.433884,0.309017,0.978148,0.5,-0.207912,1.224647e-16,-0.866025,-1.0,0 days 00:00:00.015627,0.951057,-0.900969,2899043,None,4,NaN,4,0.965311,NaN,php[8788] | PHP Warning: PHP Startup: Unable t...,NaN
9,-0.433884,0.309017,0.978148,0.5,-0.207912,1.224647e-16,-0.866025,-1.0,0 days 00:00:00.015624,0.951057,-0.900969,2899044,None,4,NaN,4,0.965311,NaN,php[7804] | PHP Warning: PHP Startup: Unable t...,NaN

In [10]:
application_transformer.fit_transform(application_training_df.head(100))

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1967.61it/s]
Batches: 100%|██████████| 4/4 [00:05<00:00,  1.41s/it]

array([[2.02890180e+01, 0.00000000e+00, 1.00000000e+00, ...,
        4.00000000e+00, 9.65311345e-01,            nan],
       [2.66288800e+00, 0.00000000e+00, 1.00000000e+00, ...,
        4.00000000e+00, 9.65311345e-01,            nan],
       [6.27950000e-02, 0.00000000e+00, 1.00000000e+00, ...,
        4.00000000e+00, 9.65311345e-01,            nan],
       ...,
       [1.17448427e+02, 0.00000000e+00, 1.00000000e+00, ...,
        4.00000000e+00, 9.65311345e-01,            nan],
       [1.56210000e-02, 0.00000000e+00, 1.00000000e+00, ...,
        4.00000000e+00, 9.65311345e-01,            nan],
       [2.34377000e-01, 0.00000000e+00, 1.00000000e+00, ...,
        4.00000000e+00, 9.65311345e-01,            nan]], shape=(100, 51))

# Security

In [11]:
security_training_records = parse_security(security_evtx_path)

security_training_records[0]

{'timestamp': {'day_sin': np.float64(0.9749279121818236),
  'second_sin': np.float64(0.6691306063588582),
  'minute_cos': np.float64(2.83276944882399e-16),
  'hour_sin': np.float64(0.0),
  'minute_sin': np.float64(1.0),
  'month_sin': np.float64(1.2246467991473532e-16),
  'hour_cos': np.float64(1.0),
  'month_cos': np.float64(-1.0),
  'deltatime': Timedelta('0 days 00:00:01.096741'),
  'second_cos': np.float64(0.7431448254773942),
  'day_cos': np.float64(-0.22252093395631434)},
 'profile': {'event_record_id': 34978816,
  'correlation_activity_id': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01',
  'event_id': 4624,
  'version': 2,
  'previous_event_id': 4624,
  'event_id_frequency': np.float64(0.20136019830928623),
  'execution_thread_id': 5960},
 'data': {'process_name': 'C:\\Windows\\System32\\svchost.exe',
  'value': None,
  'actor': 'S-1-5-18',
  'permission': 'Negotiate',
  'logon_id': '0x3e7',
  'status': None,
  'entity': 'S-1-5-21-3333335972-2113272682-612058519-500',
  'process_id': None,
  'ip': '-',
  'context': 4}}

In [12]:
flat_security_training_record = [{**record['timestamp'], **record['profile'], **record['data']} for record in security_training_records]

flat_security_training_record[0]

{'day_sin': np.float64(0.9749279121818236),
 'second_sin': np.float64(0.6691306063588582),
 'minute_cos': np.float64(2.83276944882399e-16),
 'hour_sin': np.float64(0.0),
 'minute_sin': np.float64(1.0),
 'month_sin': np.float64(1.2246467991473532e-16),
 'hour_cos': np.float64(1.0),
 'month_cos': np.float64(-1.0),
 'deltatime': Timedelta('0 days 00:00:01.096741'),
 'second_cos': np.float64(0.7431448254773942),
 'day_cos': np.float64(-0.22252093395631434),
 'event_record_id': 34978816,
 'correlation_activity_id': 'F1DAB952-E970-0004-5DB9-DAF170E9DC01',
 'event_id': 4624,
 'version': 2,
 'previous_event_id': 4624,
 'event_id_frequency': np.float64(0.20136019830928623),
 'execution_thread_id': 5960,
 'process_name': 'C:\\Windows\\System32\\svchost.exe',
 'value': None,
 'actor': 'S-1-5-18',
 'permission': 'Negotiate',
 'logon_id': '0x3e7',
 'status': None,
 'entity': 'S-1-5-21-3333335972-2113272682-612058519-500',
 'process_id': None,
 'ip': '-',
 'context': 4}

In [13]:
security_training_df = pd.DataFrame(flat_security_training_record)

security_training_df.head(10)

,day_sin,second_sin,minute_cos,hour_sin,minute_sin,month_sin,hour_cos,month_cos,deltatime,second_cos,...,process_name,value,actor,permission,logon_id,status,entity,process_id,ip,context
0,0.974928,0.669131,2.832769e-16,0.0,1.000000,1.224647e-16,1.0,-1.0,0 days 00:00:01.096741,0.743145,...,C:\Windows\System32\svchost.exe,None,S-1-5-18,Negotiate,0x3e7,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,-,4
1,0.974928,0.669131,2.832769e-16,0.0,1.000000,1.224647e-16,1.0,-1.0,0 days 00:00:00.000008,0.743145,...,NaN,None,NaN,SeSecurityPrivilege\r\n\t\t\tSeTakeOwnershipPr...,0x77061c91,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,NaN,None
2,0.974928,0.743145,2.832769e-16,0.0,1.000000,1.224647e-16,1.0,-1.0,0 days 00:00:00.671212,0.669131,...,NaN,None,NaN,NaN,0x77061c91,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,NaN,4
3,0.974928,-0.500000,2.832769e-16,0.0,1.000000,1.224647e-16,1.0,-1.0,0 days 00:00:46.664296,0.866025,...,NaN,None,NaN,NaN,0x770579fb,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,NaN,4
4,0.974928,0.000000,-1.045285e-01,0.0,0.994522,1.224647e-16,1.0,-1.0,0 days 00:00:05.480553,1.000000,...,NaN,None,NaN,NaN,NaN,0x0,Administrateur,None,NaN,None
5,0.974928,0.000000,-1.045285e-01,0.0,0.994522,1.224647e-16,1.0,-1.0,0 days 00:00:00.000708,1.000000,...,C:\Windows\System32\svchost.exe,None,S-1-5-18,NaN,0x3e7,NaN,Administrateur,None,-,localhost
6,0.974928,0.000000,-1.045285e-01,0.0,0.994522,1.224647e-16,1.0,-1.0,0 days 00:00:00.000026,1.000000,...,C:\Windows\System32\svchost.exe,None,S-1-5-18,Negotiate,0x3e7,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,-,4
7,0.974928,0.000000,-1.045285e-01,0.0,0.994522,1.224647e-16,1.0,-1.0,0 days 00:00:00.000008,1.000000,...,NaN,None,NaN,SeSecurityPrivilege\r\n\t\t\tSeTakeOwnershipPr...,0x77067629,NaN,S-1-5-21-3333335972-2113272682-612058519-500,None,NaN,None
8,0.974928,0.207912,-1.045285e-01,0.0,0.994522,1.224647e-16,1.0,-1.0,0 days 00:00:02.147107,0.978148,...,NaN,None,NaN,NaN,NaN,0x0,Administrateur,None,NaN,None
9,0.974928,0.207912,-1.045285e-01,0.0,0.994522,1.224647e-16,1.0,-1.0,0 days 00:00:00.001451,0.978148,...,NaN,None,NaN,NaN,NaN,0x0,Administrateur,None,NaN,None

In [14]:
security_transformer.fit_transform(security_training_df)

ValueError: cannot convert float NaN to integer